# Generated by Django 4.2.8 on 2023-12-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_studentid_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Text',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
