# Generated by Django 4.2.8 on 2023-12-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_id_alter_student_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Text',
            field=models.CharField(max_length=100),
        ),
    ]
